export type Skill = {
  name: string;
  type: "Passive" | "Skill 1" | "Skill 2" | "Ultimate";
  descKm: string;
  descEn: string;
  cooldown?: string;
  mana?: string;
};
export type HeroSkills = {
  passive: Skill;
  s1: Skill;
  s2: Skill;
  ult: Skill;
};
export const HERO_SKILLS: Record<string, HeroSkills> = {
  lancelot: {
    passive: { name: "Soul Cutter", type: "Passive", descKm: "បង្កើន damage បន្ទាប់ពី dash", descEn: "Increases damage after dashing" },
    s1: { name: "Puncture", type: "Skill 1", descKm: "Dash ទៅមុខ បង្កការខូចខាត ៣ ដង", descEn: "Dashes forward 3 times", cooldown: "8s", mana: "60" },
    s2: { name: "Thorned Rose", type: "Skill 2", descKm: "Swing ដាវយ៉ាងលឿន បង្កើត shield", descEn: "Swings sword, gains shield", cooldown: "8s", mana: "60" },
    ult: { name: "Phantom Execution", type: "Ultimate", descKm: "Dash ទៅមុខ បង្កការខូចខាតខ្ពស់", descEn: "Dashes forward, high damage", cooldown: "40s", mana: "120" },
  },
  fanny: {
    passive: { name: "Cut Throat", type: "Passive", descKm: "បង្កើន damage បន្ទាប់ពីប្រើខ្សែ", descEn: "Increases damage after cables" },
    s1: { name: "Tunnel", type: "Skill 1", descKm: "បាញ់ខ្សែទៅជញ្ជាំង ដើម្បីទាញខ្លួនឯង", descEn: "Fires cable to wall", cooldown: "0s", mana: "0" },
    s2: { name: "Steel Cable", type: "Skill 2", descKm: "បាញ់ខ្សែពីរ ដើម្បីហោះលឿន", descEn: "Fires two cables to fly", cooldown: "0s", mana: "0" },
    ult: { name: "Cut Throat", type: "Ultimate", descKm: "បង្កើន damage និងល្បឿន ក្នុងរយៈពេលខ្លី", descEn: "Boosts damage and speed", cooldown: "35s", mana: "100" },
  },
  gusion: {
    passive: { name: "Dagger Specialist", type: "Passive", descKm: "ការវាយបន្ថែម damage និងបង្កើត mark", descEn: "Attacks add damage and marks" },
    s1: { name: "Sword Spike", type: "Skill 1", descKm: "បាញ់ដាវទៅមុខ បង្កការខូចខាត", descEn: "Fires dagger forward", cooldown: "6s", mana: "60" },
    s2: { name: "Shadowblade Slaughter", type: "Skill 2", descKm: "បាញ់ដាវច្រើន បង្កការខូចខាត", descEn: "Fires multiple daggers", cooldown: "8s", mana: "70" },
    ult: { name: "Incandescence", type: "Ultimate", descKm: "បំផ្ទុះ mark បង្កការខូចខាត និង blink", descEn: "Detonates marks and blinks", cooldown: "30s", mana: "100" },
  },
  ling: {
    passive: { name: "Cloud Walker", type: "Passive", descKm: "បង្កើន movement speed នៅលើជញ្ជាំង", descEn: "Increases speed on walls" },
    s1: { name: "Finch Poise", type: "Skill 1", descKm: "លោតទៅជញ្ជាំង ដើម្បីបង្កើនល្បឿន និង damage", descEn: "Leaps to wall, boosts speed", cooldown: "1s", mana: "20" },
    s2: { name: "Defiant Sword", type: "Skill 2", descKm: "វាយដាវពីរដង បង្កការខូចខាត និង slow", descEn: "Strikes twice, slows", cooldown: "6s", mana: "40" },
    ult: { name: "Tempest of Blades", type: "Ultimate", descKm: "វាយដាវលឿនៗ បង្កការខូចខាត", descEn: "Strikes rapidly", cooldown: "40s", mana: "120" },
  },
  hayabusa: {
    passive: { name: "Shadow", type: "Passive", descKm: "បង្កើន damage និងបង្កើត shadow", descEn: "Increases damage and shadows" },
    s1: { name: "Phantom Shuriken", type: "Skill 1", descKm: "បាញ់ shuriken បង្កការខូចខាត និង slow", descEn: "Throws shurikens, slows", cooldown: "7s", mana: "60" },
    s2: { name: "Quad Shadow", type: "Skill 2", descKm: "បង្កើត shadow ច្រើន ដើម្បី blink", descEn: "Creates shadows to blink", cooldown: "10s", mana: "70" },
    ult: { name: "Shadow Kill", type: "Ultimate", descKm: "ទៅរកសត្រូវ បង្កការខូចខាតច្រើនដង", descEn: "Teleports to enemies", cooldown: "45s", mana: "130" },
  },
  chou: {
    passive: { name: "Only Fast", type: "Passive", descKm: "បង្កើន movement speed បន្ទាប់ពីប្រើ skill", descEn: "Increases speed after skills" },
    s1: { name: "Jeet Kune Do", type: "Skill 1", descKm: "វាយបីដងជាប់គ្នា បង្កការខូចខាត និង slow", descEn: "Strikes three times, slows", cooldown: "6s", mana: "50" },
    s2: { name: "Shunpo", type: "Skill 2", descKm: "dash ទៅមុខ បង្កការខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "5s", mana: "40" },
    ult: { name: "Way of Dragon", type: "Ultimate", descKm: "ទាត់សត្រូវឡើងលើ បង្កការខូចខាត", descEn: "Kicks enemy upward", cooldown: "35s", mana: "100" },
  },
  aldous: {
    passive: { name: "Soul Steal", type: "Passive", descKm: "បង្កើន damage តាមរយៈ stack", descEn: "Increases damage through stacking" },
    s1: { name: "Soul Steal", type: "Skill 1", descKm: "បាញ់ថាមពល បង្កការខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Explosion", type: "Skill 2", descKm: "បង្កការខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Chase Fate", type: "Ultimate", descKm: "dash ទៅសត្រូវ បង្កការខូចខាតខ្ពស់", descEn: "Dashes to enemy, high damage", cooldown: "50s", mana: "120" },
  },
  paquito: {
    passive: { name: "Champ Stance", type: "Passive", descKm: "បន្ទាប់ពីប្រើ skill បង្កើន damage និង shield", descEn: "Increases damage and shield" },
    s1: { name: "Heavy Left Punch", type: "Skill 1", descKm: "វាយដោយក្រដាស់ បង្កការខូចខាត", descEn: "Punches forward", cooldown: "6s", mana: "50" },
    s2: { name: "Jab Combo", type: "Skill 2", descKm: "វាយបីដងជាប់គ្នា បង្កការខូចខាត", descEn: "Strikes three times", cooldown: "7s", mana: "60" },
    ult: { name: "Knockout Strike", type: "Ultimate", descKm: "វាយខ្លាំងៗ បង្កការខូចខាតខ្ពស់ និង stun", descEn: "Powerful strike and stun", cooldown: "40s", mana: "120" },
  },
  arlott: {
    passive: { name: "Demon Wrath", type: "Passive", descKm: "បង្កើន damage និង speed បន្ទាប់ពី skill", descEn: "Increases damage and speed" },
    s1: { name: "Demon Slash", type: "Skill 1", descKm: "វាយដាវបង្កការខូចខាត និង slow", descEn: "Slashes forward, slows", cooldown: "7s", mana: "60" },
    s2: { name: "Demon Grasp", type: "Skill 2", descKm: "ទាញសត្រូវជិតៗ និង stun", descEn: "Pulls nearby enemies and stuns", cooldown: "11s", mana: "70" },
    ult: { name: "Demon Vengeance", type: "Ultimate", descKm: "Dash ទៅសត្រូវ បង្កការខូចខាតខ្ពស់", descEn: "Dashes to enemy, high damage", cooldown: "45s", mana: "130" },
  },
  yu_zhong: {
    passive: { name: "Black Dragon Wrath", type: "Passive", descKm: "បង្កើន damage និង shield", descEn: "Increases damage and shield" },
    s1: { name: "Dragon Will", type: "Skill 1", descKm: "វាយដោយក្រចក បង្កការខូចខាត", descEn: "Strikes with claws", cooldown: "7s", mana: "60" },
    s2: { name: "Soul Link", type: "Skill 2", descKm: "dash ទៅមុខ បង្កការខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "9s", mana: "70" },
    ult: { name: "Black Dragon Descends", type: "Ultimate", descKm: "ក្លាយជានាគ បង្កការខូចខាតខ្ពស់", descEn: "Transforms into dragon", cooldown: "50s", mana: "130" },
  },  atlas: {
    passive: { name: "Frigid Breath", type: "Passive", descKm: "ការវាយធម្មតាបង្កើត Frigid Breath", descEn: "Basic attacks build Frigid Breath" },
    s1: { name: "Frigid Breath", type: "Skill 1", descKm: "បាញ់ Frigid Breath ទៅមុខ និង slow", descEn: "Fires Frigid Breath forward", cooldown: "7s", mana: "60" },
    s2: { name: "Perfect Match", type: "Skill 2", descKm: "ទាញសត្រូវ ២ នាក់ចូលគ្នា", descEn: "Pulls two enemies together", cooldown: "12s", mana: "80" },
    ult: { name: "Fatal Links", type: "Ultimate", descKm: "បាញ់ខ្សែសង្វាក់ទៅសត្រូវ និង stun", descEn: "Fires chains, stunning enemies", cooldown: "60s", mana: "150" },
  },
  tigreal: {
    passive: { name: "Fearless", type: "Passive", descKm: "បង្កើនភាពធន់ និងខូចខាត", descEn: "Increases defense and damage" },
    s1: { name: "Attack Wave", type: "Skill 1", descKm: "វាយដោយដាវ បង្កការខូចខាត និង slow", descEn: "Swings sword, slows", cooldown: "7s", mana: "60" },
    s2: { name: "Sacred Assault", type: "Skill 2", descKm: "dash ទៅមុខ បង្កការខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "10s", mana: "70" },
    ult: { name: "Implosion", type: "Ultimate", descKm: "ទាញសត្រូវចូលគ្នា និង stun", descEn: "Pulls enemies together and stuns", cooldown: "60s", mana: "150" },
  },
  khufra: {
    passive: { name: "Tyrant Revenge", type: "Passive", descKm: "បង្កើនភាពធន់ និងខូចខាតពេលសត្រូវ dash", descEn: "Increases defense vs dashes" },
    s1: { name: "Bouncing Ball", type: "Skill 1", descKm: "បាញ់បាល់ បង្កការខូចខាត និង stun", descEn: "Fires ball, stuns", cooldown: "8s", mana: "70" },
    s2: { name: "Tyrant Revenge", type: "Skill 2", descKm: "លោតឡើងលើ រួចធ្លាក់ចុះ", descEn: "Leaps and slams down", cooldown: "10s", mana: "80" },
    ult: { name: "Tyrant Seal", type: "Ultimate", descKm: "បង្កើតតំបន់ហាម blink និង dash", descEn: "Creates zone preventing blink", cooldown: "55s", mana: "150" },
  },
  franco: {
    passive: { name: "Wasteland Force", type: "Passive", descKm: "បង្កើន HP regen ពេលគ្មានសត្រូវជិត", descEn: "Increases HP when no enemies nearby" },
    s1: { name: "Iron Hook", type: "Skill 1", descKm: "បាញ់ខ្សែទាញសត្រូវមករកខ្លួន", descEn: "Fires hook that pulls enemies", cooldown: "11s", mana: "70" },
    s2: { name: "Fury of Deep", type: "Skill 2", descKm: "បង្កើតរលកសំឡេង និង slow", descEn: "Creates sound wave, slows", cooldown: "12s", mana: "80" },
    ult: { name: "Bloody Hunt", type: "Ultimate", descKm: "ចាប់សត្រូវ និងផ្លាស់ទីតាំងគេ", descEn: "Grabs enemy and repositions", cooldown: "55s", mana: "120" },
  },
  gatotkaca: {
    passive: { name: "Steel Bones", type: "Passive", descKm: "បង្កើន defense និងខូចខាត", descEn: "Increases defense and damage" },
    s1: { name: "Blast Iron Fist", type: "Skill 1", descKm: "វាយដោយក្រដាស់ បង្កការខូចខាត", descEn: "Punches forward", cooldown: "7s", mana: "60" },
    s2: { name: "Unbreakable", type: "Skill 2", descKm: "បង្កើត shield និងខូចខាត", descEn: "Gains shield and deals damage", cooldown: "10s", mana: "70" },
    ult: { name: "Avatar of Sentinel", type: "Ultimate", descKm: "ហោះឡើងលើ និងធ្លាក់ចុះ", descEn: "Flies up and crashes down", cooldown: "55s", mana: "140" },
  },
  valir: {
    passive: { name: "Ashen Hair", type: "Passive", descKm: "បង្កើន damage និង knock back", descEn: "Increases damage and knockback" },
    s1: { name: "Fire Breath", type: "Skill 1", descKm: "បាញ់ភ្លើង បង្កការខូចខាត និង slow", descEn: "Breathes fire, slows", cooldown: "6s", mana: "60" },
    s2: { name: "Searing Torrent", type: "Skill 2", descKm: "បង្កើតរលកភ្លើង និង knock back", descEn: "Creates fire waves, knockback", cooldown: "9s", mana: "80" },
    ult: { name: "Inferno Blast", type: "Ultimate", descKm: "បង្កើតភ្លើងធំ ខូចខាតខ្ពស់", descEn: "Massive fire blast", cooldown: "50s", mana: "140" },
  },
  kagura: {
    passive: { name: "Frosty Breeze", type: "Passive", descKm: "បង្កើន damage តាមរយៈ skill", descEn: "Increases damage through skills" },
    s1: { name: "Breathe of Anima", type: "Skill 1", descKm: "បាញ់ថាមពល បង្កការខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Soul Scroll", type: "Skill 2", descKm: "បង្កការខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Yin Yang Overturn", type: "Ultimate", descKm: "បង្កការខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  lunox: {
    passive: { name: "Dreamer", type: "Passive", descKm: "បង្កើន damage តាម order/chaos", descEn: "Increases damage through order/chaos" },
    s1: { name: "Chaos Assault", type: "Skill 1", descKm: "បាញ់ថាមពល បង្កការខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Order Beam", type: "Skill 2", descKm: "បង្កការខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Cosmic Fission", type: "Ultimate", descKm: "បង្កការខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  eudora: {
    passive: { name: "Superconductor", type: "Passive", descKm: "បង្កើន damage ពេលវាយដោយ skill", descEn: "Increases damage with skills" },
    s1: { name: "Electric Arrow", type: "Skill 1", descKm: "បាញ់ថាមពល បង្កការខូចខាត", descEn: "Fires energy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Ball Lightning", type: "Skill 2", descKm: "បង្កការខូចខាត និង stun", descEn: "Deals damage and stuns", cooldown: "9s", mana: "70" },
    ult: { name: "Thunder Wrath", type: "Ultimate", descKm: "បង្កការខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  harith: {
    passive: { name: "Key of Insight", type: "Passive", descKm: "បង្កើន shield ពេលវាយ", descEn: "Gains shield when attacking" },
    s1: { name: "Synchro", type: "Skill 1", descKm: "dash ទៅមុខ បង្កការខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Chrono Dash", type: "Skill 2", descKm: "dash ទៅមុខ បង្កការខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Time Journey", type: "Ultimate", descKm: "បង្កើត shield និង immunity", descEn: "Grants shield and immunity", cooldown: "45s", mana: "120" },
  },  beatrix: {
    passive: { name: "Weapon Master", type: "Passive", descKm: "ប្រើអាវុធច្រើនប្រភេទ", descEn: "Uses multiple weapons" },
    s1: { name: "Nibiru", type: "Skill 1", descKm: "បាញ់គ្រាប់ធំ ខូចខាតខ្ពស់", descEn: "Fires large bullet", cooldown: "5s", mana: "50" },
    s2: { name: "Mechanical Genius", type: "Skill 2", descKm: "dash ទៅមុខ និងប្តូរអាវុធ", descEn: "Dashes forward and switches weapon", cooldown: "8s", mana: "60" },
    ult: { name: "Nibiru Enhanced", type: "Ultimate", descKm: "បាញ់គ្រាប់ផ្ទុះ ខូចខាតខ្ពស់", descEn: "Fires explosive shot", cooldown: "40s", mana: "120" },
  },
  melissa: {
    passive: { name: "Muddlet", type: "Passive", descKm: "បង្កើត Muddlet ជួយវាយ", descEn: "Summons Muddlet" },
    s1: { name: "Field of Thorns", type: "Skill 1", descKm: "បង្កើតតំបន់ ខូចខាត និង slow", descEn: "Creates damage zone, slows", cooldown: "9s", mana: "70" },
    s2: { name: "Echo Strike", type: "Skill 2", descKm: "បាញ់ថាមពល និង knock back", descEn: "Fires energy and knocks back", cooldown: "11s", mana: "80" },
    ult: { name: "Muddlet Wrath", type: "Ultimate", descKm: "បង្កើន attack speed", descEn: "Boosts attack speed", cooldown: "50s", mana: "130" },
  },
  wanwan: {
    passive: { name: "Tiger Pace", type: "Passive", descKm: "បង្កើន damage និងល្បឿន", descEn: "Increases damage and speed" },
    s1: { name: "Needles in Flowers", type: "Skill 1", descKm: "បាញ់ដាវច្រើន ខូចខាត", descEn: "Throws multiple darts", cooldown: "7s", mana: "60" },
    s2: { name: "Swallow Path", type: "Skill 2", descKm: "លោតទៅមុខ និង slow", descEn: "Leaps forward and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Crossbow of Tang", type: "Ultimate", descKm: "ខូចខាតខ្ពស់ និង stun", descEn: "High damage and stuns", cooldown: "45s", mana: "120" },
  },
  claude: {
    passive: { name: "Battle Side-by-side", type: "Passive", descKm: "Dexter ជួយវាយសត្រូវ", descEn: "Dexter helps attack" },
    s1: { name: "Art of Thievery", type: "Skill 1", descKm: "បាញ់ និងលួចល្បឿន", descEn: "Fires and steals speed", cooldown: "9s", mana: "70" },
    s2: { name: "Battle Mirror Image", type: "Skill 2", descKm: "dash និងបង្កើត clone", descEn: "Dashes and creates clone", cooldown: "11s", mana: "80" },
    ult: { name: "Blazing Duet", type: "Ultimate", descKm: "បាញ់ថាមពលខ្លាំង ខូចខាតខ្ពស់", descEn: "Fires powerful energy", cooldown: "55s", mana: "150" },
  },
  layla: {
    passive: { name: "Malefic Gunner", type: "Passive", descKm: "បង្កើន damage ពេលឆ្ងាយ", descEn: "Increases damage when far" },
    s1: { name: "Malefic Bomb", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Void Projectile", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Destruction Rush", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  angela: {
    passive: { name: "Smart Heart", type: "Passive", descKm: "បង្កើន magic power និង shield", descEn: "Increases magic power and shield" },
    s1: { name: "Love Waves", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត និង slow", descEn: "Fires energy, slows", cooldown: "6s", mana: "70" },
    s2: { name: "Puppet on String", type: "Skill 2", descKm: "ភ្ជាប់ទៅសត្រូវ និង slow", descEn: "Links to enemy and slows", cooldown: "10s", mana: "80" },
    ult: { name: "Heartguard", type: "Ultimate", descKm: "ភ្ជាប់ទៅសម្ព័ន្ធមិត្ត និង shield", descEn: "Attaches to ally with shield", cooldown: "60s", mana: "150" },
  },
  estes: {
    passive: { name: "Scripture of Healer", type: "Passive", descKm: "បង្កើន HP regen និង healing", descEn: "Increases HP regen and healing" },
    s1: { name: "Moonlight Immersion", type: "Skill 1", descKm: "ភ្ជាប់ទៅសម្ព័ន្ធមិត្ត ព្យាបាល HP", descEn: "Links to ally, heals HP", cooldown: "8s", mana: "70" },
    s2: { name: "Domain of Moon Goddess", type: "Skill 2", descKm: "តំបន់ព្យាបាលសម្ព័ន្ធមិត្ត", descEn: "Creates healing area", cooldown: "12s", mana: "100" },
    ult: { name: "Blessing of Moon Goddess", type: "Ultimate", descKm: "ព្យាបាលសម្ព័ន្ធមិត្តទាំងអស់", descEn: "Heals all allies in area", cooldown: "55s", mana: "180" },
  },
  rafaela: {
    passive: { name: "Light of Blessing", type: "Passive", descKm: "បង្កើន HP regen", descEn: "Increases HP regen" },
    s1: { name: "Light of Retribution", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "60" },
    s2: { name: "Holy Blessing", type: "Skill 2", descKm: "ព្យាបាលក្រុម និងបង្កើនល្បឿន", descEn: "Heals team and boosts speed", cooldown: "9s", mana: "80" },
    ult: { name: "Holy Baptism", type: "Ultimate", descKm: "ព្យាបាលសម្ព័ន្ធមិត្តទាំងអស់", descEn: "Heals all allies", cooldown: "55s", mana: "150" },
  },
  mathilda: {
    passive: { name: "Ancestral Gift", type: "Passive", descKm: "បង្កើន speed និង damage", descEn: "Increases speed and damage" },
    s1: { name: "Ancient Strength", type: "Skill 1", descKm: "វាយខូចខាត និង shield", descEn: "Strikes, gains shield", cooldown: "7s", mana: "60" },
    s2: { name: "Guiding Wind", type: "Skill 2", descKm: "ភ្ជាប់ទៅសម្ព័ន្ធមិត្ត និងល្បឿន", descEn: "Links to ally and boosts speed", cooldown: "10s", mana: "80" },
    ult: { name: "Wings of Sanctuary", type: "Ultimate", descKm: "ហោះទៅសម្ព័ន្ធមិត្ត និង shield", descEn: "Flies to ally with shield", cooldown: "55s", mana: "140" },
  },
  floryn: {
    passive: { name: "Dew", type: "Passive", descKm: "បង្កើត Dew ជួយព្យាបាល", descEn: "Spawns Dew to heal allies" },
    s1: { name: "Sow", type: "Skill 1", descKm: "បាញ់ថាមពល និង slow", descEn: "Fires energy and slows", cooldown: "6s", mana: "60" },
    s2: { name: "Sprout", type: "Skill 2", descKm: "តំបន់ព្យាបាលសម្ព័ន្ធមិត្ត", descEn: "Creates healing area", cooldown: "9s", mana: "80" },
    ult: { name: "Blossom", type: "Ultimate", descKm: "ព្យាបាលសម្ព័ន្ធមិត្តទាំងអស់", descEn: "Heals all allies", cooldown: "50s", mana: "150" },
  },  alucard: {
    passive: { name: "Pursuit", type: "Passive", descKm: "បង្កើន damage ពេលវាយសត្រូវតែមួយ", descEn: "Increases damage on single target" },
    s1: { name: "Groundsplitter", type: "Skill 1", descKm: "dash ទៅមុខ បង្កការខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Whirlwind Slash", type: "Skill 2", descKm: "វិលខ្លួន បង្កការខូចខាត", descEn: "Spins around, deals damage", cooldown: "7s", mana: "60" },
    ult: { name: "Fission Wave", type: "Ultimate", descKm: "ខូចខាតខ្ពស់ និង lifesteal", descEn: "High damage and lifesteal", cooldown: "40s", mana: "110" },
  },
  dyrroth: {
    passive: { name: "Wrath of Abyss", type: "Passive", descKm: "បង្កើន damage ពេល HP តិច", descEn: "Increases damage at low HP" },
    s1: { name: "Burst Strike", type: "Skill 1", descKm: "វាយដាវ បង្កការខូចខាត", descEn: "Slashes enemy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Spectre Step", type: "Skill 2", descKm: "dash ទៅមុខ បង្កការខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Abyss Wrath", type: "Ultimate", descKm: "ខូចខាតខ្ពស់ និង lifesteal", descEn: "High damage and lifesteal", cooldown: "45s", mana: "120" },
  },
  ruby: {
    passive: { name: "Let Dance", type: "Passive", descKm: "បង្កើន HP regen និង lifesteal", descEn: "Increases HP regen and lifesteal" },
    s1: { name: "Be Good", type: "Skill 1", descKm: "វាយដោយកូនកាំបិត ខូចខាត", descEn: "Strikes with scythe", cooldown: "6s", mana: "50" },
    s2: { name: "Dont Run Wolf King", type: "Skill 2", descKm: "dash ទៅមុខ និង slow", descEn: "Dashes forward and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Im Offended", type: "Ultimate", descKm: "ទាញសត្រូវ ខូចខាតខ្ពស់", descEn: "Pulls enemies, high damage", cooldown: "45s", mana: "120" },
  },
  zilong: {
    passive: { name: "Dragon Blessing", type: "Passive", descKm: "បង្កើន attack speed", descEn: "Increases attack speed" },
    s1: { name: "Spear Flip", type: "Skill 1", descKm: "វាយដោយលំពែង ខូចខាត", descEn: "Strikes with spear", cooldown: "6s", mana: "50" },
    s2: { name: "Spear Strike", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward", cooldown: "8s", mana: "60" },
    ult: { name: "Supreme Warrior", type: "Ultimate", descKm: "បង្កើន attack speed និង speed", descEn: "Increases attack speed and speed", cooldown: "40s", mana: "110" },
  },
  xborg: {
    passive: { name: "Armor Recycle", type: "Passive", descKm: "បង្កើន armor និង HP regen", descEn: "Increases armor and HP regen" },
    s1: { name: "Fire Missile", type: "Skill 1", descKm: "បាញ់ missile ខូចខាត", descEn: "Fires missile, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Cyclone Sweep", type: "Skill 2", descKm: "វិលខ្លួន ខូចខាត", descEn: "Spins around, deals damage", cooldown: "9s", mana: "70" },
    ult: { name: "Firaga Armor", type: "Ultimate", descKm: "បាញ់ភ្លើង ខូចខាតខ្ពស់", descEn: "Fires flames, high damage", cooldown: "50s", mana: "130" },
  },
  akai: {
    passive: { name: "Tai Chi", type: "Passive", descKm: "បង្កើនភាពធន់ និងខូចខាត", descEn: "Increases defense and damage" },
    s1: { name: "Headbutt", type: "Skill 1", descKm: "វាយដោយក្បាល និង slow", descEn: "Headbutts forward, slows", cooldown: "8s", mana: "60" },
    s2: { name: "Blender", type: "Skill 2", descKm: "វិលខ្លួន ខូចខាត និង slow", descEn: "Spins around, slows", cooldown: "10s", mana: "70" },
    ult: { name: "Hurricane Dance", type: "Ultimate", descKm: "វិលខ្លួនលឿន ទាញសត្រូវ និង stun", descEn: "Spins rapidly, pulls and stuns", cooldown: "45s", mana: "120" },
  },
  hylos: {
    passive: { name: "Thickened Blood", type: "Passive", descKm: "បង្កើន HP តាម mana", descEn: "Increases HP through mana" },
    s1: { name: "Ring of Punishment", type: "Skill 1", descKm: "បង្កើតរង្វង់ និង slow", descEn: "Creates ring and slows", cooldown: "8s", mana: "60" },
    s2: { name: "Glorious Pathway", type: "Skill 2", descKm: "បង្កើតផ្លូវ និង slow", descEn: "Creates path and slows", cooldown: "11s", mana: "80" },
    ult: { name: "Grand Warden", type: "Ultimate", descKm: "ព្យាបាលខ្លួន និងខូចខាត", descEn: "Heals self and deals damage", cooldown: "50s", mana: "140" },
  },
  johnson: {
    passive: { name: "Electro Airbag", type: "Passive", descKm: "បង្កើត shield ពេល HP តិច", descEn: "Gains shield at low HP" },
    s1: { name: "Missile Launch", type: "Skill 1", descKm: "បាញ់ missile និង slow", descEn: "Fires missile and slows", cooldown: "7s", mana: "60" },
    s2: { name: "Iron Punch", type: "Skill 2", descKm: "វាយដោយក្រដាស់ ខូចខាត", descEn: "Punches enemy, deals damage", cooldown: "9s", mana: "70" },
    ult: { name: "Rapid Transformation", type: "Ultimate", descKm: "ក្លាយជាឡាន ខូចខាតខ្ពស់", descEn: "Transforms into car", cooldown: "60s", mana: "150" },
  },
  alice: {
    passive: { name: "Blood Aroma", type: "Passive", descKm: "បង្កើន HP regen ពេលវាយ", descEn: "Increases HP regen when attacking" },
    s1: { name: "Flowing Blood", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Blood Aroma", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Blood Ode", type: "Ultimate", descKm: "ខូចខាតខ្ពស់ និង lifesteal", descEn: "High damage and lifesteal", cooldown: "50s", mana: "130" },
  },
  cyclops: {
    passive: { name: "Starlight", type: "Passive", descKm: "បង្កើន damage តាម stack", descEn: "Increases damage through stacking" },
    s1: { name: "Stardust Shock", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Planets Attack", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Eye of Storm", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  valentina: {
    passive: { name: "Arcane Teachings", type: "Passive", descKm: "បង្កើន EXP និង shield", descEn: "Gains extra EXP and shield" },
    s1: { name: "Shadow Strike", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "60" },
    s2: { name: "Arcane Barrage", type: "Skill 2", descKm: "បង្កើតតំបន់ និង slow", descEn: "Creates zone and slows", cooldown: "10s", mana: "80" },
    ult: { name: "Arcane Mastery", type: "Ultimate", descKm: "Copy ultimate សត្រូវ", descEn: "Copies enemy ultimate", cooldown: "60s", mana: "150" },
  },
  miya: {
    passive: { name: "Moon Blessing", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Fallen Arrow", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Arrow of Eclipse", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Hidden Moon", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  granger: {
    passive: { name: "Demon Hunter", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Rhapsody", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Rondo", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Death Sonata", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  moskov: {
    passive: { name: "Spear of Death", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Spear of Death", type: "Skill 1", descKm: "បាញ់លំពែង ខូចខាត", descEn: "Fires spear, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Spear of Quiescence", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Spear of Destruction", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  aamon: {
    passive: { name: "Camouflage", type: "Passive", descKm: "បង្កើន damage និង invisibility", descEn: "Increases damage and invisibility" },
    s1: { name: "Soul Shard", type: "Skill 1", descKm: "បាញ់ shard ខូចខាត", descEn: "Fires shard, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Shadow Step", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Vengeance", type: "Ultimate", descKm: "ខូចខាតខ្ពស់ និង lifesteal", descEn: "High damage and lifesteal", cooldown: "45s", mana: "120" },
  },
  harley: {
    passive: { name: "Magic Master", type: "Passive", descKm: "បង្កើន magic power", descEn: "Increases magic power" },
    s1: { name: "Poker Trick", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Space Escape", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Deadly Magic", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "40s", mana: "110" },
  },  baxia: {
    passive: { name: "Shield of Dungeon", type: "Passive", descKm: "បង្កើត shield ពេលត្រូវវាយ", descEn: "Gains shield when attacked" },
    s1: { name: "Baxia Mark", type: "Skill 1", descKm: "បាញ់ថាមពល និង mark", descEn: "Fires energy and marks", cooldown: "7s", mana: "60" },
    s2: { name: "Fiery Rush", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "10s", mana: "70" },
    ult: { name: "Torrential Force", type: "Ultimate", descKm: "ទាញសត្រូវចូលគ្នា", descEn: "Pulls enemies together", cooldown: "55s", mana: "140" },
  },
  belerick: {
    passive: { name: "Ancient Seed", type: "Passive", descKm: "បង្កើត Seed ជុំវិញខ្លួន", descEn: "Spawns Seeds around" },
    s1: { name: "Ancient Seed", type: "Skill 1", descKm: "បាញ់ Seed ទៅសត្រូវ", descEn: "Fires Seed, deals damage", cooldown: "8s", mana: "70" },
    s2: { name: "Nature Strike", type: "Skill 2", descKm: "ទាញសត្រូវជិតៗ និង shield", descEn: "Pulls nearby enemies, gains shield", cooldown: "10s", mana: "80" },
    ult: { name: "Ancient Seedling", type: "Ultimate", descKm: "តំបន់ខូចខាត និង shield", descEn: "Creates damage area and shield", cooldown: "50s", mana: "130" },
  },
  edith: {
    passive: { name: "Wraith", type: "Passive", descKm: "បង្កើន defense និង magic power", descEn: "Increases defense and magic power" },
    s1: { name: "Wraith Shout", type: "Skill 1", descKm: "ខូចខាត និង taunt", descEn: "Deals damage and taunts", cooldown: "8s", mana: "60" },
    s2: { name: "Wraith Charge", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "11s", mana: "70" },
    ult: { name: "Wraith Form", type: "Ultimate", descKm: "ផ្លាស់ប្តូរជា marksman", descEn: "Transforms into marksman", cooldown: "55s", mana: "140" },
  },
  argus: {
    passive: { name: "Warmonger", type: "Passive", descKm: "បង្កើន damage ពេល HP តិច", descEn: "Increases damage at low HP" },
    s1: { name: "Demonic Grip", type: "Skill 1", descKm: "បាញ់ថាមពល និង slow", descEn: "Fires energy and slows", cooldown: "7s", mana: "60" },
    s2: { name: "Metamorphosis", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "9s", mana: "70" },
    ult: { name: "Dark Angel Rage", type: "Ultimate", descKm: "មិនអាចស្លាប់ និងខូចខាត", descEn: "Immune to death", cooldown: "60s", mana: "150" },
  },
  balmond: {
    passive: { name: "Bloodthirst", type: "Passive", descKm: "បង្កើន HP regen ពេលវាយ", descEn: "Increases HP regen when attacking" },
    s1: { name: "Soul Lock", type: "Skill 1", descKm: "វាយដោយពូថៅ ខូចខាត", descEn: "Swings axe, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Cyclone Sweep", type: "Skill 2", descKm: "វិលខ្លួន ខូចខាត", descEn: "Spins around, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Lethal Counter", type: "Ultimate", descKm: "វាយខ្លាំង ខូចខាតខ្ពស់", descEn: "Powerful strike, high damage", cooldown: "40s", mana: "110" },
  },
  freya: {
    passive: { name: "Valkyrie", type: "Passive", descKm: "បង្កើន shield ពេលវាយ", descEn: "Gains shield when attacking" },
    s1: { name: "Leap of Faith", type: "Skill 1", descKm: "លោតទៅមុខ ខូចខាត", descEn: "Leaps forward, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Spirit Combo", type: "Skill 2", descKm: "វាយច្រើនដង ខូចខាត", descEn: "Strikes multiple times", cooldown: "9s", mana: "70" },
    ult: { name: "Valkyrie Descent", type: "Ultimate", descKm: "បង្កើន damage និង shield", descEn: "Increases damage and shield", cooldown: "50s", mana: "130" },
  },
  jawhead: {
    passive: { name: "Rocket Fuel", type: "Passive", descKm: "បង្កើន HP និង damage", descEn: "Increases HP and damage" },
    s1: { name: "Rocket Fist", type: "Skill 1", descKm: "បាញ់ដៃ ខូចខាត", descEn: "Fires fist, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Smart Nails", type: "Skill 2", descKm: "វាយដោយក្រចក ខូចខាត", descEn: "Strikes with nails", cooldown: "9s", mana: "70" },
    ult: { name: "Unstoppable Force", type: "Ultimate", descKm: "ចាប់សត្រូវ និងផ្លាស់ទីតាំង", descEn: "Grabs enemy and repositions", cooldown: "50s", mana: "130" },
  },
  martis: {
    passive: { name: "Ashura Wrath", type: "Passive", descKm: "បង្កើន damage និងល្បឿន", descEn: "Increases damage and speed" },
    s1: { name: "Ashura Wrath", type: "Skill 1", descKm: "វាយដាវ ខូចខាត", descEn: "Slashes enemy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Mortal Coil", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Decimation", type: "Ultimate", descKm: "វាយខ្លាំង ខូចខាតខ្ពស់", descEn: "Powerful strike, high damage", cooldown: "45s", mana: "120" },
  },
  phoveus: {
    passive: { name: "Demonic Force", type: "Passive", descKm: "បង្កើន damage ពេលត្រូវវាយ", descEn: "Increases damage when attacked" },
    s1: { name: "Malefic Terror", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Astral Echo", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "9s", mana: "70" },
    ult: { name: "Demonic Descent", type: "Ultimate", descKm: "លោតឡើង និងធ្លាក់ចុះ", descEn: "Leaps and slams", cooldown: "50s", mana: "130" },
  },
  sun: {
    passive: { name: "Simian God", type: "Passive", descKm: "បង្កើន damage និង clone", descEn: "Increases damage and clones" },
    s1: { name: "Endless Variety", type: "Skill 1", descKm: "វាយដោយដំបង ខូចខាត", descEn: "Strikes with staff", cooldown: "6s", mana: "50" },
    s2: { name: "Swift Exchange", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Clone Techniques", type: "Ultimate", descKm: "បង្កើត clone ជួយវាយ", descEn: "Creates clones to attack", cooldown: "45s", mana: "120" },
  },
  thamuz: {
    passive: { name: "Molten Core", type: "Passive", descKm: "បង្កើន damage និង lifesteal", descEn: "Increases damage and lifesteal" },
    s1: { name: "Molten Smash", type: "Skill 1", descKm: "វាយដោយពូថៅ ខូចខាត", descEn: "Swings axe, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Chasm", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Cauterize", type: "Ultimate", descKm: "បង្កើន lifesteal និង damage", descEn: "Increases lifesteal and damage", cooldown: "50s", mana: "130" },
  },
  terizla: {
    passive: { name: "Smith Forge", type: "Passive", descKm: "បង្កើន damage និង slow", descEn: "Increases damage and slows" },
    s1: { name: "Reckless Hammer", type: "Skill 1", descKm: "វាយដោយញញួរ ខូចខាត", descEn: "Swings hammer, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Condemnation", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Execution Strike", type: "Ultimate", descKm: "វាយខ្លាំង ខូចខាតខ្ពស់", descEn: "Powerful strike, high damage", cooldown: "50s", mana: "130" },
  },
  aurora: {
    passive: { name: "Pride of Ice", type: "Passive", descKm: "ខូចខាត និង freeze", descEn: "Deals damage and freezes" },
    s1: { name: "Frost Shock", type: "Skill 1", descKm: "បាញ់ទឹកកក ខូចខាត", descEn: "Fires ice, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Bitter Frost", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Cold Destruction", type: "Ultimate", descKm: "ខូចខាតខ្ពស់ និង freeze", descEn: "High damage and freezes", cooldown: "50s", mana: "130" },
  },
  cecilion: {
    passive: { name: "Overflow", type: "Passive", descKm: "បង្កើន magic power តាម stack", descEn: "Increases magic power through stacking" },
    s1: { name: "Bat Impact", type: "Skill 1", descKm: "បាញ់ bat ខូចខាត", descEn: "Fires bats, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Sanguine Claw", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Bats Feast", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  gord: {
    passive: { name: "Mystic Favor", type: "Passive", descKm: "បង្កើន damage តាម stack", descEn: "Increases damage through stacking" },
    s1: { name: "Mystic Projectile", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Mystic Blast", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Mystic Favor", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  pharsa: {
    passive: { name: "Spiritual Unity", type: "Passive", descKm: "បង្កើន magic power", descEn: "Increases magic power" },
    s1: { name: "Curse of Crow", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "7s", mana: "70" },
    s2: { name: "Wings by Wings", type: "Skill 2", descKm: "ហោះទៅទីតាំងថ្មី", descEn: "Flies to new location", cooldown: "10s", mana: "80" },
    ult: { name: "Feathered Air Strike", type: "Ultimate", descKm: "ហោះឡើងលើ បាញ់ថាមពល", descEn: "Flies up and fires", cooldown: "45s", mana: "150" },
  },
  vale: {
    passive: { name: "Windtalker", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Wind Blade", type: "Skill 1", descKm: "បាញ់ខ្យល់ ខូចខាត", descEn: "Fires wind, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Wind Blast", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Wind Storm", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  yve: {
    passive: { name: "Galactic Energy", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Galactic Blast", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Star Field", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Real World Manipulation", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "55s", mana: "140" },
  },
  zhask: {
    passive: { name: "Nightmaric Spawn", type: "Passive", descKm: "បង្កើត spawn", descEn: "Creates a spawn" },
    s1: { name: "Nightmaric Spawn", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Swarm", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Primal Wrath", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  natan: {
    passive: { name: "Theory of Everything", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Superposition", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Interference", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Entropy", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },  barats: {
    passive: { name: "Big Guy", type: "Passive", descKm: "បង្កើន size និង defense", descEn: "Increases size and defense" },
    s1: { name: "So-Called Teamwork", type: "Skill 1", descKm: "បាញ់កាំភ្លើង ខូចខាត", descEn: "Fires gun, deals damage", cooldown: "8s", mana: "60" },
    s2: { name: "Missile Em", type: "Skill 2", descKm: "បាញ់ missile ខូចខាត", descEn: "Fires missile, deals damage", cooldown: "12s", mana: "80" },
    ult: { name: "Detona", type: "Ultimate", descKm: "ខាំសត្រូវ និងទាញ", descEn: "Bites enemy and drags", cooldown: "50s", mana: "150" },
  },
  gloo: {
    passive: { name: "Gloo Goo", type: "Passive", descKm: "បង្កើត Goo ខូចខាត", descEn: "Spawns damaging Goo" },
    s1: { name: "Slam Stretch Roll", type: "Skill 1", descKm: "វាយបង្កការខូចខាត និង slow", descEn: "Strikes and slows", cooldown: "7s", mana: "60" },
    s2: { name: "Grab", type: "Skill 2", descKm: "ចាប់សត្រូវ និងខូចខាត", descEn: "Grabs enemy, deals damage", cooldown: "10s", mana: "70" },
    ult: { name: "Split Split", type: "Ultimate", descKm: "បំបែកខ្លួន និងខូចខាត", descEn: "Splits into pieces", cooldown: "55s", mana: "140" },
  },
  grock: {
    passive: { name: "Earthen Force", type: "Passive", descKm: "បង្កើន defense ជិតជញ្ជាំង", descEn: "Increases defense near walls" },
    s1: { name: "Power of Nature", type: "Skill 1", descKm: "វាយដោយដំបង", descEn: "Strikes with staff", cooldown: "7s", mana: "60" },
    s2: { name: "Guardian Barrier", type: "Skill 2", descKm: "បង្កើតជញ្ជាំង និង dash", descEn: "Creates wall and dashes", cooldown: "10s", mana: "70" },
    ult: { name: "Wild Charge", type: "Ultimate", descKm: "dash ទៅមុខ និង knock up", descEn: "Dashes forward and knocks up", cooldown: "50s", mana: "130" },
  },
  hilda: {
    passive: { name: "Blessing of Wilderness", type: "Passive", descKm: "បង្កើន HP regen ក្នុងព្រៃ", descEn: "Increases HP regen in bush" },
    s1: { name: "Combat Ritual", type: "Skill 1", descKm: "វាយបង្កការខូចខាត និងបង្កើនល្បឿន", descEn: "Strikes and boosts speed", cooldown: "7s", mana: "60" },
    s2: { name: "Art of Hunting", type: "Skill 2", descKm: "វាយសត្រូវ និង slow", descEn: "Strikes and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Power of Wildness", type: "Ultimate", descKm: "វាយខ្លាំង និង stun", descEn: "Powerful strike and stun", cooldown: "45s", mana: "120" },
  },
  lolita: {
    passive: { name: "Nimble", type: "Passive", descKm: "បង្កើន speed ពេលការពារ", descEn: "Increases speed when defending" },
    s1: { name: "Charge", type: "Skill 1", descKm: "បាញ់ថាមពល និង slow", descEn: "Fires energy and slows", cooldown: "7s", mana: "60" },
    s2: { name: "Guardian Bulwark", type: "Skill 2", descKm: "បង្កើត shield ការពារ", descEn: "Creates shield blocking projectiles", cooldown: "12s", mana: "80" },
    ult: { name: "Nova Blast", type: "Ultimate", descKm: "បាញ់ថាមពលធំ និង stun", descEn: "Fires large energy and stuns", cooldown: "55s", mana: "150" },
  },
  masha: {
    passive: { name: "Ancient Strength", type: "Passive", descKm: "មាន HP បីដង", descEn: "Has three HP bars" },
    s1: { name: "Wild Charge", type: "Skill 1", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "7s", mana: "50" },
    s2: { name: "Howl Shock", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "60" },
    ult: { name: "Thunderclap", type: "Ultimate", descKm: "វាយខ្លាំង ខូចខាតខ្ពស់", descEn: "Powerful strike", cooldown: "45s", mana: "120" },
  },
  minotaur: {
    passive: { name: "Rage", type: "Passive", descKm: "បង្កើន rage ពេលវាយ", descEn: "Builds rage when attacking" },
    s1: { name: "Despair Stomp", type: "Skill 1", descKm: "ជាន់ដី និង slow", descEn: "Stomps ground and slows", cooldown: "8s", mana: "60" },
    s2: { name: "Motivation Roar", type: "Skill 2", descKm: "ព្យាបាលខ្លួន និងខូចខាត", descEn: "Heals self and deals damage", cooldown: "12s", mana: "80" },
    ult: { name: "Minoan Fury", type: "Ultimate", descKm: "វាយខ្លាំង និង knock up", descEn: "Powerful strike and knocks up", cooldown: "55s", mana: "150" },
  },
  uranus: {
    passive: { name: "Radiance", type: "Passive", descKm: "បង្កើន HP regen ពេលត្រូវវាយ", descEn: "Increases HP regen when attacked" },
    s1: { name: "Ionic Edge", type: "Skill 1", descKm: "បាញ់ថាមពល និង slow", descEn: "Fires energy and slows", cooldown: "7s", mana: "60" },
    s2: { name: "Transcendent Ward", type: "Skill 2", descKm: "បង្កើត shield និងខូចខាត", descEn: "Gains shield and deals damage", cooldown: "10s", mana: "70" },
    ult: { name: "Consecration", type: "Ultimate", descKm: "ខូចខាត និងព្យាបាលខ្លួន", descEn: "Deals damage and heals self", cooldown: "50s", mana: "130" },
  },
  aulus: {
    passive: { name: "Fighting Spirit", type: "Passive", descKm: "បង្កើន damage តាម stack", descEn: "Increases damage through stacking" },
    s1: { name: "Axe Swing", type: "Skill 1", descKm: "វាយដោយពូថៅ ខូចខាត", descEn: "Swings axe, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Power of Axe", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Undying Fury", type: "Ultimate", descKm: "បង្កើន attack speed និង damage", descEn: "Increases attack speed and damage", cooldown: "50s", mana: "130" },
  },
  badang: {
    passive: { name: "Fist of Justice", type: "Passive", descKm: "បង្កើត fist mark ពេលវាយ", descEn: "Creates fist marks when attacking" },
    s1: { name: "Fist Wind", type: "Skill 1", descKm: "បាញ់ fist ខូចខាត", descEn: "Fires fist, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Fist Break", type: "Skill 2", descKm: "dash ទៅមុខ និង stun", descEn: "Dashes forward and stuns", cooldown: "9s", mana: "60" },
    ult: { name: "Fist of Glory", type: "Ultimate", descKm: "បង្កើតជញ្ជាំង ខូចខាតខ្ពស់", descEn: "Creates wall, high damage", cooldown: "50s", mana: "130" },
  },
  guinevere: {
    passive: { name: "Spatial Migration", type: "Passive", descKm: "បង្កើន damage បន្ទាប់ពី skill", descEn: "Increases damage after skills" },
    s1: { name: "Energy Wave", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Violet Requiem", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "9s", mana: "60" },
    ult: { name: "Spatial Leap", type: "Ultimate", descKm: "លោតទៅអាកាស ខូចខាតខ្ពស់", descEn: "Leaps into air, high damage", cooldown: "50s", mana: "130" },
  },
  khaleed: {
    passive: { name: "Sand Walk", type: "Passive", descKm: "បង្កើន HP regen និង defense", descEn: "Increases HP regen and defense" },
    s1: { name: "Desert Tornado", type: "Skill 1", descKm: "វាយដាវ ខូចខាត", descEn: "Slashes enemy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Rising Sand", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Sandstorm", type: "Ultimate", descKm: "បង្កើត sandstorm ខូចខាត", descEn: "Creates sandstorm, deals damage", cooldown: "50s", mana: "130" },
  },
  lapu_lapu: {
    passive: { name: "Hero Blood", type: "Passive", descKm: "បង្កើន damage និង defense", descEn: "Increases damage and defense" },
    s1: { name: "Balisong Slash", type: "Skill 1", descKm: "វាយដាវ ខូចខាត", descEn: "Slashes enemy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Twin Blades", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Brave Combat", type: "Ultimate", descKm: "បង្កើន damage និង attack speed", descEn: "Increases damage and attack speed", cooldown: "50s", mana: "130" },
  },
  leomord: {
    passive: { name: "Shadow Stride", type: "Passive", descKm: "បង្កើន damage ពេលលើសត្វ", descEn: "Increases damage when mounted" },
    s1: { name: "Death Ride", type: "Skill 1", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Phantom Steed", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Barbiel Wrath", type: "Ultimate", descKm: "ទាញសត្រូវ ខូចខាតខ្ពស់", descEn: "Pulls enemy, high damage", cooldown: "50s", mana: "130" },
  },
  minsitthar: {
    passive: { name: "Mark of King", type: "Passive", descKm: "បង្កើន damage និង gold", descEn: "Increases damage and gold" },
    s1: { name: "Spear of Glory", type: "Skill 1", descKm: "បាញ់លំពែង ខូចខាត", descEn: "Fires spear, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Shield of Glory", type: "Skill 2", descKm: "បង្កើត shield និងខូចខាត", descEn: "Gains shield and deals damage", cooldown: "9s", mana: "70" },
    ult: { name: "King Calling", type: "Ultimate", descKm: "ទាញសត្រូវ ខូចខាត", descEn: "Pulls enemies, deals damage", cooldown: "50s", mana: "130" },
  },
  roger: {
    passive: { name: "Full Moon Curse", type: "Passive", descKm: "បង្កើន damage ពេលពេញព្រះចន្ទ", descEn: "Increases damage on full moon" },
    s1: { name: "Hunter Steps", type: "Skill 1", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Hunter Snare", type: "Skill 2", descKm: "ដាក់អន្ទាក់ ខូចខាត", descEn: "Sets trap, deals damage", cooldown: "10s", mana: "70" },
    ult: { name: "Wolf Transformation", type: "Ultimate", descKm: "ប្តូរជាចចក ខូចខាត", descEn: "Transforms into wolf", cooldown: "45s", mana: "120" },
  },
  silvanna: {
    passive: { name: "Knight Vow", type: "Passive", descKm: "បង្កើន damage និង shield", descEn: "Increases damage and shield" },
    s1: { name: "Cometic Lance", type: "Skill 1", descKm: "បាញ់លំពែង ខូចខាត", descEn: "Fires lance, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Spiral Strangling", type: "Skill 2", descKm: "ទាញសត្រូវ ខូចខាត", descEn: "Pulls enemies, deals damage", cooldown: "9s", mana: "70" },
    ult: { name: "Imperial Justice", type: "Ultimate", descKm: "បង្កើតតំបន់ និង slow", descEn: "Creates zone and slows", cooldown: "50s", mana: "130" },
  },
  julian: {
    passive: { name: "Sword Master", type: "Passive", descKm: "បង្កើន damage តាម combo", descEn: "Increases damage through combo" },
    s1: { name: "Sword Slash", type: "Skill 1", descKm: "វាយដាវ ខូចខាត", descEn: "Slashes enemy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Blade Dash", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Ultimate Sword", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  suyou: {
    passive: { name: "Swift Blade", type: "Passive", descKm: "បង្កើន speed និង damage", descEn: "Increases speed and damage" },
    s1: { name: "Quick Slash", type: "Skill 1", descKm: "វាយដាវ ខូចខាត", descEn: "Slashes enemy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Wind Step", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Storm Blade", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  benedetta: {
    passive: { name: "Shadow", type: "Passive", descKm: "បង្កើន speed និង damage", descEn: "Increases speed and damage" },
    s1: { name: "Phantom Slash", type: "Skill 1", descKm: "វាយដាវ ខូចខាត", descEn: "Slashes enemy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Alecto Charge", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Rapid Blade", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  hanzo: {
    passive: { name: "Ninjutsu", type: "Passive", descKm: "បង្កើន damage និង shadow", descEn: "Increases damage and shadows" },
    s1: { name: "Demon Feast", type: "Skill 1", descKm: "បាញ់ shuriken ខូចខាត", descEn: "Throws shurikens, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Soul Reap", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "9s", mana: "70" },
    ult: { name: "Pinnacle Ninja", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  helcurt: {
    passive: { name: "Shadow Rush", type: "Passive", descKm: "បង្កើន speed និង invisibility", descEn: "Increases speed and invisibility" },
    s1: { name: "Race Advantage", type: "Skill 1", descKm: "បាញ់ stinger ខូចខាត", descEn: "Fires stinger, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Dark Night Falls", type: "Skill 2", descKm: "បង្កើតភាពងងឹត", descEn: "Creates darkness", cooldown: "10s", mana: "70" },
    ult: { name: "Dark Night Falls", type: "Ultimate", descKm: "dash ទៅមុខ ខូចខាតខ្ពស់", descEn: "Dashes forward, high damage", cooldown: "50s", mana: "130" },
  },
  joy: {
    passive: { name: "Energy Rush", type: "Passive", descKm: "បង្កើន damage និងល្បឿន", descEn: "Increases damage and speed" },
    s1: { name: "Beat Wave", type: "Skill 1", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "7s", mana: "50" },
    s2: { name: "Beat Combo", type: "Skill 2", descKm: "វាយច្រើនដង ខូចខាត", descEn: "Strikes multiple times", cooldown: "6s", mana: "50" },
    ult: { name: "Electrifying Beat", type: "Ultimate", descKm: "បង្កើន damage និង immunity", descEn: "Boosts damage and immunity", cooldown: "50s", mana: "120" },
  },
  kadita: {
    passive: { name: "Ocean Blessing", type: "Passive", descKm: "បង្កើន HP regen", descEn: "Increases HP regen" },
    s1: { name: "Ocean Oddity", type: "Skill 1", descKm: "បាញ់រលក ខូចខាត", descEn: "Fires wave, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Rough Waves", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "9s", mana: "70" },
    ult: { name: "Rough Waves", type: "Ultimate", descKm: "ខូចខាតខ្ពស់ និង slow", descEn: "High damage and slows", cooldown: "45s", mana: "120" },
  },
  karina: {
    passive: { name: "Shadow Rush", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Dance of Blades", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Dance of Death", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Shadow Assault", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "40s", mana: "110" },
  },
  lesley: {
    passive: { name: "Lethal Shot", type: "Passive", descKm: "បង្កើន damage ពេលមិនឃើញ", descEn: "Increases damage when unseen" },
    s1: { name: "Master of Camouflage", type: "Skill 1", descKm: "បាញ់ច្បាស់ ខូចខាត", descEn: "Fires precise shot, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Tactical Grenade", type: "Skill 2", descKm: "បាញ់គ្រាប់បំផ្ទុះ", descEn: "Fires grenade, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Ultimate Snipe", type: "Ultimate", descKm: "បាញ់ឆ្ងាយ ខូចខាតខ្ពស់", descEn: "Long-range shot, high damage", cooldown: "45s", mana: "120" },
  },
  natalia: {
    passive: { name: "Assassin Instinct", type: "Passive", descKm: "បង្កើន damage ពេល invisibility", descEn: "Increases damage when invisible" },
    s1: { name: "Claw Strike", type: "Skill 1", descKm: "វាយដោយក្រចក ខូចខាត", descEn: "Strikes with claws, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Smoke Bomb", type: "Skill 2", descKm: "បង្កើតផ្សែង invisibility", descEn: "Creates smoke for invisibility", cooldown: "10s", mana: "70" },
    ult: { name: "Silent Kill", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "40s", mana: "110" },
  },
  nolan: {
    passive: { name: "Sword Master", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Blade Slash", type: "Skill 1", descKm: "វាយដាវ ខូចខាត", descEn: "Slashes enemy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Shadow Dash", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Ultimate Strike", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  saber: {
    passive: { name: "Enemy Bane", type: "Passive", descKm: "បង្កើន damage ពេលវាយ skill", descEn: "Increases damage with skills" },
    s1: { name: "Orbiting Swords", type: "Skill 1", descKm: "បង្កើតដាវវិល ខូចខាត", descEn: "Creates orbiting swords", cooldown: "7s", mana: "60" },
    s2: { name: "Charge", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "9s", mana: "70" },
    ult: { name: "Triple Sweep", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "40s", mana: "110" },
  },
  selena: {
    passive: { name: "Mark of Shadow", type: "Passive", descKm: "បង្កើត mark ពេលវាយ", descEn: "Creates marks when attacking" },
    s1: { name: "Abyssal Trap", type: "Skill 1", descKm: "ដាក់អន្ទាក់ ខូចខាត", descEn: "Sets trap, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Soul Eater", type: "Skill 2", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "9s", mana: "70" },
    ult: { name: "Shadow Rush", type: "Ultimate", descKm: "dash ទៅមុខ ខូចខាតខ្ពស់", descEn: "Dashes forward, high damage", cooldown: "45s", mana: "120" },
  },
  yin: {
    passive: { name: "Martial Master", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Slash", type: "Skill 1", descKm: "វាយបង្កការខូចខាត", descEn: "Strikes enemy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Charge", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Ultimate Form", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },  change: {
    passive: { name: "Starmoon Shockwave", type: "Passive", descKm: "បង្កើន damage តាម stack", descEn: "Increases damage through stacking" },
    s1: { name: "Starmoon Shockwave", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Crescent Moon", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Meteor Shower", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  diggie: {
    passive: { name: "Young Again", type: "Passive", descKm: "មិនអាចស្លាប់", descEn: "Cannot die" },
    s1: { name: "Time Bomb", type: "Skill 1", descKm: "ដាក់គ្រាប់បំផ្ទុះ", descEn: "Sets time bomb, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Time Journey", type: "Skill 2", descKm: "បង្កើត shield និង speed", descEn: "Grants shield and speed", cooldown: "10s", mana: "70" },
    ult: { name: "Time Reversal", type: "Ultimate", descKm: "បញ្ឈប់ការវាយ និង immunity", descEn: "Stops attacks and grants immunity", cooldown: "55s", mana: "140" },
  },
  faramis: {
    passive: { name: "Undead", type: "Passive", descKm: "បង្កើន HP regen", descEn: "Increases HP regen" },
    s1: { name: "Ghostly Mark", type: "Skill 1", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "7s", mana: "60" },
    s2: { name: "Shadow Energy", type: "Skill 2", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "9s", mana: "70" },
    ult: { name: "Cult Altar", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "55s", mana: "140" },
  },
  luo_yi: {
    passive: { name: "Yin Yang Gathering", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Duality", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Dispersion", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Yin Yang Overturn", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  lylia: {
    passive: { name: "Shadow Energy", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Shadow Energy", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Shadow Blast", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Shadow Trap", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  nana: {
    passive: { name: "Molina Gift", type: "Passive", descKm: "ត្រឡប់មកវិញជា Molina", descEn: "Returns as Molina" },
    s1: { name: "Molina Blast", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Molina Trap", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Molina Blast", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  novaria: {
    passive: { name: "Star Trail", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Astral Echo", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Star Trail", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Astral Portal", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  odette: {
    passive: { name: "Lover Symphony", type: "Passive", descKm: "បង្កើន damage ពេលជិត Lancelot", descEn: "Increases damage near Lancelot" },
    s1: { name: "Swan Song", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Blade of Enchantment", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Swan Song", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "55s", mana: "140" },
  },
  vexana: {
    passive: { name: "Necromancy", type: "Passive", descKm: "បង្កើត puppet", descEn: "Creates a puppet" },
    s1: { name: "Chomp", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Puppet", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Puppet King", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  xavier: {
    passive: { name: "Transcendence", type: "Passive", descKm: "បង្កើន magic power", descEn: "Increases magic power" },
    s1: { name: "Foresight", type: "Skill 1", descKm: "បង្កើតតំបន់ឃើញសត្រូវ", descEn: "Creates revealing zone", cooldown: "8s", mana: "80" },
    s2: { name: "Mystic Field", type: "Skill 2", descKm: "បង្កើតតំបន់ និង slow", descEn: "Creates zone and slows", cooldown: "10s", mana: "90" },
    ult: { name: "Dawning Light", type: "Ultimate", descKm: "បាញ់ថាមពលឆ្ងាយ", descEn: "Fires long-range beam", cooldown: "60s", mana: "150" },
  },
  zhuxin: {
    passive: { name: "Crimson Butterfly", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Crimson Butterfly", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Butterfly Dance", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Butterfly Storm", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  brody: {
    passive: { name: "Hunter", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Abyss Bolt", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Abyss Trail", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Abyss Reaper", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  bruno: {
    passive: { name: "Volley", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Volley", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Flying Tackle", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Worldie", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  clint: {
    passive: { name: "Double Shot", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Blast", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Smoke Bomb", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Grenade", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  hanabi: {
    passive: { name: "Petal", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Petal", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Soul Scroll", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Higanbana", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  irithel: {
    passive: { name: "Jungle Heart", type: "Passive", descKm: "បង្កើន damage និង speed", descEn: "Increases damage and speed" },
    s1: { name: "Wild Rush", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Beast Step", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Heavy Crossbow", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  ixia: {
    passive: { name: "Ocean Wrath", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Bubble", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Tide", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Tsunami", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  karrie: {
    passive: { name: "Lightwheel Mark", type: "Passive", descKm: "បង្កើត mark", descEn: "Creates marks" },
    s1: { name: "Rising Dragon", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Phantom Step", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Speedy Lightwheel", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  popol_and_kupa: {
    passive: { name: "Friend of Forest", type: "Passive", descKm: "Kupa ជួយវាយ", descEn: "Kupa helps attack" },
    s1: { name: "Kupa Help", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Kupa Attack", type: "Skill 2", descKm: "Kupa វាយសត្រូវ", descEn: "Kupa attacks enemies", cooldown: "8s", mana: "60" },
    ult: { name: "Kupa Transform", type: "Ultimate", descKm: "Kupa ក្លាយជាធំ", descEn: "Kupa transforms", cooldown: "45s", mana: "120" },
  },
  "yi_sun-shin": {
    passive: { name: "Heavenly Vow", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Spear Strike", type: "Skill 1", descKm: "បាញ់លំពែង ខូចខាត", descEn: "Fires spear, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Bloodlust", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Turtle Ship", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },  chip: {
    passive: { name: "Portal", type: "Passive", descKm: "បង្កើត portal សម្រាប់ផ្លាស់ទី", descEn: "Creates portals for mobility" },
    s1: { name: "Whack", type: "Skill 1", descKm: "វាយបង្កការខូចខាត", descEn: "Strikes enemy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Portal", type: "Skill 2", descKm: "បង្កើត portal សម្រាប់ក្រុម", descEn: "Creates portal for allies", cooldown: "15s", mana: "80" },
    ult: { name: "Big Portal", type: "Ultimate", descKm: "បង្កើត portal ធំ", descEn: "Creates large portal", cooldown: "60s", mana: "150" },
  },
  cici: {
    passive: { name: "Bouncing Back", type: "Passive", descKm: "បង្កើន damage និង lifesteal", descEn: "Increases damage and lifesteal" },
    s1: { name: "Yo-Yo Swing", type: "Skill 1", descKm: "វាយដោយ yo-yo ខូចខាត", descEn: "Swings yo-yo, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Stage Fright", type: "Skill 2", descKm: "dash និងខូចខាត", descEn: "Dashes and deals damage", cooldown: "10s", mana: "70" },
    ult: { name: "Acrobatic Show", type: "Ultimate", descKm: "វិលខ្លួន និង slow", descEn: "Spins around and slows", cooldown: "50s", mana: "130" },
  },
  lukas: {
    passive: { name: "Undying", type: "Passive", descKm: "បង្កើន defense ពេល HP តិច", descEn: "Increases defense at low HP" },
    s1: { name: "Slash", type: "Skill 1", descKm: "វាយដាវ ខូចខាត", descEn: "Slashes enemy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Charge", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "9s", mana: "60" },
    ult: { name: "Wrath", type: "Ultimate", descKm: "ខូចខាតខ្ពស់ និង stun", descEn: "High damage and stuns", cooldown: "50s", mana: "130" },
  },
  kalea: {
    passive: { name: "Ocean Blessing", type: "Passive", descKm: "បង្កើន healing និង shield", descEn: "Increases healing and shield" },
    s1: { name: "Wave", type: "Skill 1", descKm: "បាញ់រលក ខូចខាត", descEn: "Fires wave, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Tide", type: "Skill 2", descKm: "ព្យាបាលក្រុម និងខូចខាត", descEn: "Heals team and deals damage", cooldown: "11s", mana: "80" },
    ult: { name: "Tsunami", type: "Ultimate", descKm: "ខូចខាតខ្ពស់ និង knock up", descEn: "High damage and knocks up", cooldown: "55s", mana: "140" },
  },
  fredrinn: {
    passive: { name: "Crystal Energy", type: "Passive", descKm: "បង្កើត Crystal Energy", descEn: "Builds Crystal Energy" },
    s1: { name: "Bull Eye", type: "Skill 1", descKm: "បាញ់ថាមពល និង slow", descEn: "Fires energy and slows", cooldown: "7s", mana: "60" },
    s2: { name: "Burning Rage", type: "Skill 2", descKm: "ខូចខាត និង shield", descEn: "Deals damage and gains shield", cooldown: "10s", mana: "70" },
    ult: { name: "Appraiser Wrath", type: "Ultimate", descKm: "វាយខ្លាំង និង stun", descEn: "Powerful strike and stun", cooldown: "45s", mana: "130" },
  },
  alpha: {
    passive: { name: "Beta", type: "Passive", descKm: "បង្កើន damage និង healing", descEn: "Increases damage and healing" },
    s1: { name: "Alpha Slash", type: "Skill 1", descKm: "វាយបង្កការខូចខាត", descEn: "Strikes enemy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Spear of Alpha", type: "Skill 2", descKm: "ទាញសត្រូវ ខូចខាត", descEn: "Pulls enemy, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Alpha Strike", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  kimmy: {
    passive: { name: "Chemist", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Chemist Spray", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Energetic Burst", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Chemistry Lesson", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  obsidia: {
    passive: { name: "Dark Power", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Dark Arrow", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Dark Blast", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Dark Storm", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  hirara: {
    passive: { name: "Spirit Link", type: "Passive", descKm: "បង្កើន damage និង healing", descEn: "Increases damage and healing" },
    s1: { name: "Spirit Wave", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Spirit Dash", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Spirit Storm", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  marcel: {
    passive: { name: "Void Walker", type: "Passive", descKm: "បង្កើន damage និង shield", descEn: "Increases damage and shield" },
    s1: { name: "Void Slash", type: "Skill 1", descKm: "វាយបង្កការខូចខាត", descEn: "Strikes enemy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Void Dash", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Void Strike", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  sora: {
    passive: { name: "Sky Dancer", type: "Passive", descKm: "បង្កើន speed និង damage", descEn: "Increases speed and damage" },
    s1: { name: "Wind Blade", type: "Skill 1", descKm: "វាយបង្កការខូចខាត", descEn: "Strikes enemy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Sky Dash", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Sky Storm", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  zetian: {
    passive: { name: "Empress Wrath", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Imperial Strike", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Empress Command", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Empress Decree", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  zilong_fighter: {
    passive: { name: "Dragon Blessing", type: "Passive", descKm: "បង្កើន attack speed", descEn: "Increases attack speed" },
    s1: { name: "Spear Flip", type: "Skill 1", descKm: "វាយដោយលំពែង", descEn: "Strikes with spear", cooldown: "6s", mana: "50" },
    s2: { name: "Spear Strike", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Supreme Warrior", type: "Ultimate", descKm: "បង្កើន attack speed និង speed", descEn: "Increases attack speed and speed", cooldown: "40s", mana: "110" },
  },  carmilla: {
    passive: { name: "Vampire Bond", type: "Passive", descKm: "បង្កើត link ជាមួយសម្ព័ន្ធមិត្ត និង shield", descEn: "Links to ally and grants shield" },
    s1: { name: "Crimson Flower", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "60" },
    s2: { name: "Bloody Kiss", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Vampire's Kiss", type: "Ultimate", descKm: "បង្កើត link ជាមួយសត្រូវ ខូចខាត", descEn: "Links to enemy and damages", cooldown: "50s", mana: "130" },
  },
  esmeralda: {
    passive: { name: "Starmoon Casket", type: "Passive", descKm: "បង្កើត shield ពេលវាយ", descEn: "Builds shield when attacking" },
    s1: { name: "Frostmoon Shield", type: "Skill 1", descKm: "បង្កើត shield និងខូចខាត", descEn: "Creates shield and deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Stardust Dance", type: "Skill 2", descKm: "dash និងខូចខាត", descEn: "Dashes and deals damage", cooldown: "8s", mana: "70" },
    ult: { name: "Starmoon Spell", type: "Ultimate", descKm: "ខូចខាតខ្ពស់ និង shield", descEn: "High damage and shield", cooldown: "45s", mana: "120" },
  },
  kaja: {
    passive: { name: "Rise of the Abyss", type: "Passive", descKm: "បង្កើត shield ពេលត្រូវវាយ", descEn: "Gains shield when attacked" },
    s1: { name: "Ring of Order", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Divine Judgement", type: "Skill 2", descKm: "ទាញសត្រូវ ខូចខាត", descEn: "Pulls enemy, deals damage", cooldown: "10s", mana: "80" },
    ult: { name: "Might of Judgement", type: "Ultimate", descKm: "ចាប់សត្រូវ និងទាញ", descEn: "Grabs enemy and pulls", cooldown: "55s", mana: "150" },
  },
  bane: {
    passive: { name: "Shark Bite", type: "Passive", descKm: "បង្កើន damage ពេលវាយ", descEn: "Increases damage when attacking" },
    s1: { name: "Crab Claw Cannon", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Rum Punch", type: "Skill 2", descKm: "វាយបង្កការខូចខាត និង slow", descEn: "Strikes, deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Deadly Catch", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  harrow: {
    passive: { name: "Umbral Blessing", type: "Passive", descKm: "បង្កើន damage តាម stack", descEn: "Increases damage through stacking" },
    s1: { name: "Lightning Bolt", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Umbral Dash", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Umbral Storm", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  moscow: {
    passive: { name: "Spear of Death", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Spear of Death", type: "Skill 1", descKm: "បាញ់លំពែង ខូចខាត", descEn: "Fires spear, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Spear of Quiescence", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "8s", mana: "60" },
    ult: { name: "Spear of Destruction", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "45s", mana: "120" },
  },
  bea: {
    passive: { name: "Weapon Master", type: "Passive", descKm: "ប្រើអាវុធច្រើនប្រភេទ", descEn: "Uses multiple weapons" },
    s1: { name: "Nibiru", type: "Skill 1", descKm: "បាញ់គ្រាប់ធំ ខូចខាតខ្ពស់", descEn: "Fires large bullet, high damage", cooldown: "5s", mana: "50" },
    s2: { name: "Mechanical Genius", type: "Skill 2", descKm: "dash និងប្តូរអាវុធ", descEn: "Dashes and switches weapon", cooldown: "8s", mana: "60" },
    ult: { name: "Nibiru Enhanced", type: "Ultimate", descKm: "បាញ់គ្រាប់ផ្ទុះ ខូចខាតខ្ពស់", descEn: "Fires explosive shot", cooldown: "40s", mana: "120" },
  },
  yve_: {
    passive: { name: "Galactic Energy", type: "Passive", descKm: "បង្កើន damage", descEn: "Increases damage" },
    s1: { name: "Galactic Blast", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Star Field", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Real World Manipulation", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "55s", mana: "140" },
  },
  gord_: {
    passive: { name: "Mystic Favor", type: "Passive", descKm: "បង្កើន damage តាម stack", descEn: "Increases damage through stacking" },
    s1: { name: "Mystic Projectile", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Mystic Blast", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Mystic Favor", type: "Ultimate", descKm: "ខូចខាតខ្ពស់", descEn: "Deals high damage", cooldown: "50s", mana: "130" },
  },
  angela_: {
    passive: { name: "Smart Heart", type: "Passive", descKm: "បង្កើន magic power និង shield", descEn: "Increases magic power and shield" },
    s1: { name: "Love Waves", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត និង slow", descEn: "Fires energy, slows", cooldown: "6s", mana: "70" },
    s2: { name: "Puppet on String", type: "Skill 2", descKm: "ភ្ជាប់ទៅសត្រូវ និង slow", descEn: "Links to enemy and slows", cooldown: "10s", mana: "80" },
    ult: { name: "Heartguard", type: "Ultimate", descKm: "ភ្ជាប់ទៅសម្ព័ន្ធមិត្ត និង shield", descEn: "Attaches to ally with shield", cooldown: "60s", mana: "150" },
  },  harith_: {
    passive: { name: "Key of Insight", type: "Passive", descKm: "បង្កើន shield ពេលវាយ", descEn: "Gains shield when attacking" },
    s1: { name: "Synchro", type: "Skill 1", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Chrono Dash", type: "Skill 2", descKm: "dash ទៅមុខ ខូចខាត", descEn: "Dashes forward, deals damage", cooldown: "8s", mana: "60" },
    ult: { name: "Time Journey", type: "Ultimate", descKm: "បង្កើត shield និង immunity", descEn: "Grants shield and immunity", cooldown: "45s", mana: "120" },
  },
  diggie_: {
    passive: { name: "Young Again", type: "Passive", descKm: "មិនអាចស្លាប់", descEn: "Cannot die" },
    s1: { name: "Time Bomb", type: "Skill 1", descKm: "ដាក់គ្រាប់បំផ្ទុះ", descEn: "Sets time bomb, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Time Journey", type: "Skill 2", descKm: "បង្កើត shield និង speed", descEn: "Grants shield and speed", cooldown: "10s", mana: "70" },
    ult: { name: "Time Reversal", type: "Ultimate", descKm: "បញ្ឈប់ការវាយ និង immunity", descEn: "Stops attacks and grants immunity", cooldown: "55s", mana: "140" },
  },
  estes_: {
    passive: { name: "Scripture of Healer", type: "Passive", descKm: "បង្កើន HP regen និង healing", descEn: "Increases HP regen and healing" },
    s1: { name: "Moonlight Immersion", type: "Skill 1", descKm: "ភ្ជាប់ទៅសម្ព័ន្ធមិត្ត ព្យាបាល HP", descEn: "Links to ally, heals HP", cooldown: "8s", mana: "70" },
    s2: { name: "Domain of Moon Goddess", type: "Skill 2", descKm: "តំបន់ព្យាបាលសម្ព័ន្ធមិត្ត", descEn: "Creates healing area", cooldown: "12s", mana: "100" },
    ult: { name: "Blessing of Moon Goddess", type: "Ultimate", descKm: "ព្យាបាលសម្ព័ន្ធមិត្តទាំងអស់", descEn: "Heals all allies in area", cooldown: "55s", mana: "180" },
  },
  floryn_: {
    passive: { name: "Dew", type: "Passive", descKm: "បង្កើត Dew ជួយព្យាបាល", descEn: "Spawns Dew to heal allies" },
    s1: { name: "Sow", type: "Skill 1", descKm: "បាញ់ថាមពល និង slow", descEn: "Fires energy and slows", cooldown: "6s", mana: "60" },
    s2: { name: "Sprout", type: "Skill 2", descKm: "តំបន់ព្យាបាលសម្ព័ន្ធមិត្ត", descEn: "Creates healing area", cooldown: "9s", mana: "80" },
    ult: { name: "Blossom", type: "Ultimate", descKm: "ព្យាបាលសម្ព័ន្ធមិត្តទាំងអស់", descEn: "Heals all allies", cooldown: "50s", mana: "150" },
  },
  mathilda_: {
    passive: { name: "Ancestral Gift", type: "Passive", descKm: "បង្កើន speed និង damage", descEn: "Increases speed and damage" },
    s1: { name: "Ancient Strength", type: "Skill 1", descKm: "វាយខូចខាត និង shield", descEn: "Strikes, gains shield", cooldown: "7s", mana: "60" },
    s2: { name: "Guiding Wind", type: "Skill 2", descKm: "ភ្ជាប់ទៅសម្ព័ន្ធមិត្ត និងល្បឿន", descEn: "Links to ally and boosts speed", cooldown: "10s", mana: "80" },
    ult: { name: "Wings of Sanctuary", type: "Ultimate", descKm: "ហោះទៅសម្ព័ន្ធមិត្ត និង shield", descEn: "Flies to ally with shield", cooldown: "55s", mana: "140" },
  },
  lolita_: {
    passive: { name: "Nimble", type: "Passive", descKm: "បង្កើន speed ពេលការពារ", descEn: "Increases speed when defending" },
    s1: { name: "Charge", type: "Skill 1", descKm: "បាញ់ថាមពល និង slow", descEn: "Fires energy and slows", cooldown: "7s", mana: "60" },
    s2: { name: "Guardian Bulwark", type: "Skill 2", descKm: "បង្កើត shield ការពារ", descEn: "Creates shield blocking projectiles", cooldown: "12s", mana: "80" },
    ult: { name: "Nova Blast", type: "Ultimate", descKm: "បាញ់ថាមពលធំ និង stun", descEn: "Fires large energy and stuns", cooldown: "55s", mana: "150" },
  },
  minotaur_: {
    passive: { name: "Rage", type: "Passive", descKm: "បង្កើន rage ពេលវាយ", descEn: "Builds rage when attacking" },
    s1: { name: "Despair Stomp", type: "Skill 1", descKm: "ជាន់ដី និង slow", descEn: "Stomps ground and slows", cooldown: "8s", mana: "60" },
    s2: { name: "Motivation Roar", type: "Skill 2", descKm: "ព្យាបាលខ្លួន និងខូចខាត", descEn: "Heals self and deals damage", cooldown: "12s", mana: "80" },
    ult: { name: "Minoan Fury", type: "Ultimate", descKm: "វាយខ្លាំង និង knock up", descEn: "Powerful strike and knocks up", cooldown: "55s", mana: "150" },
  },
  rafaela_: {
    passive: { name: "Light of Blessing", type: "Passive", descKm: "បង្កើន HP regen", descEn: "Increases HP regen" },
    s1: { name: "Light of Retribution", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "60" },
    s2: { name: "Holy Blessing", type: "Skill 2", descKm: "ព្យាបាលក្រុម និងបង្កើនល្បឿន", descEn: "Heals team and boosts speed", cooldown: "9s", mana: "80" },
    ult: { name: "Holy Baptism", type: "Ultimate", descKm: "ព្យាបាលសម្ព័ន្ធមិត្តទាំងអស់", descEn: "Heals all allies", cooldown: "55s", mana: "150" },
  },
  lapu_lapu_: {
    passive: { name: "Hero Blood", type: "Passive", descKm: "បង្កើន damage និង defense", descEn: "Increases damage and defense" },
    s1: { name: "Balisong Slash", type: "Skill 1", descKm: "វាយដាវ ខូចខាត", descEn: "Slashes enemy, deals damage", cooldown: "7s", mana: "60" },
    s2: { name: "Twin Blades", type: "Skill 2", descKm: "ខូចខាត និង slow", descEn: "Deals damage and slows", cooldown: "9s", mana: "70" },
    ult: { name: "Brave Combat", type: "Ultimate", descKm: "បង្កើន damage និង attack speed", descEn: "Increases damage and attack speed", cooldown: "50s", mana: "130" },
  },
  popol: {
    passive: { name: "Friend of Forest", type: "Passive", descKm: "Kupa ជួយវាយ", descEn: "Kupa helps attack" },
    s1: { name: "Kupa Help", type: "Skill 1", descKm: "បាញ់ថាមពល ខូចខាត", descEn: "Fires energy, deals damage", cooldown: "6s", mana: "50" },
    s2: { name: "Kupa Attack", type: "Skill 2", descKm: "Kupa វាយសត្រូវ", descEn: "Kupa attacks enemies", cooldown: "8s", mana: "60" },
    ult: { name: "Kupa Transform", type: "Ultimate", descKm: "Kupa ក្លាយជាធំ", descEn: "Kupa transforms", cooldown: "45s", mana: "120" },
  },};
export function getHeroSkills(heroId: string): HeroSkills | null {
  return HERO_SKILLS[heroId] || null;
}
