"use client";
import { useMemo, useState } from "react";
import {
  Search, Zap, Users, BookOpen, Copy, Check, RefreshCw,
  ChevronDown, Target, Sparkles, Info,
} from "lucide-react";
import { useLang } from "@/lib/i18n";
import { FadeIn } from "@/components/FadeIn";
import {
  BRANDS, POPULAR_MODELS, getModelsByBrand, findDevice,
  getTotalDevices, type DeviceTier,
} from "@/lib/ffDevices";
import {
  calculateSensitivity, PLAYSTYLE_LABELS, SENSITIVITY_ROWS,
  TIER_LABELS, type Playstyle, type SensitivityResult,
} from "@/lib/ffSensitivity";

type Tab = "generator" | "community" | "guide";

const PLAYSTYLES: Playstyle[] = ["headshot", "onetap", "clash", "br", "balanced", "sniper"];

export function SensitivityCalculator() {
  const { lang } = useLang();
  const km = lang === "km";

  const [tab, setTab] = useState<Tab>("generator");
  const [brand, setBrand] = useState<string>("");
  const [model, setModel] = useState<string>("");
  const [search, setSearch] = useState<string>("");
  const [age, setAge] = useState<string>("1");
  const [style, setStyle] = useState<Playstyle>("headshot");
  const [result, setResult] = useState<SensitivityResult | null>(null);
  const [copied, setCopied] = useState(false);

  const models = useMemo(() => (brand ? getModelsByBrand(brand) : []), [brand]);

  const currentDevice = useMemo(() => findDevice(model), [model]);

  // ─── Search filter ───
  const searchResults = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (q.length < 2) return [];
    return POPULAR_MODELS.filter((m) => m.toLowerCase().includes(q)).slice(0, 8);
  }, [search]);

  // ─── Actions ───
  function generate() {
    if (!currentDevice) return;
    const ageNum = Math.max(0, Math.min(10, parseFloat(age) || 0));
    const r = calculateSensitivity(
      currentDevice.dpi,
      currentDevice.tier,
      ageNum,
      style
    );
    setResult(r);
  }

  function reset() {
    setBrand("");
    setModel("");
    setSearch("");
    setAge("1");
    setStyle("headshot");
    setResult(null);
  }

  function pickPopular(m: string) {
    setModel(m);
    setSearch("");
    const d = findDevice(m);
    if (d) setBrand(d.brand);
  }

  async function copyResult() {
    if (!result) return;
    const lines = [
      "🎯 FREE FIRE SENSITIVITY — " + model,
      "━━━━━━━━━━━━━━━━━━━━",
      ...SENSITIVITY_ROWS.map((r) => `${r.en}: ${result[r.key]}`),
      `DPI: ${result.dpi}`,
      `Playstyle: ${PLAYSTYLE_LABELS[result.playstyle].en}`,
      "",
      "Generated by yoursite.com",
    ].join("\n");
    try {
      await navigator.clipboard.writeText(lines);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // ignore
    }
  }

  return (
    <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:py-14">
      {/* TABS */}
      <FadeIn>
        <div className="mb-8 flex flex-wrap gap-2 border-b border-line pb-1">
          {(
            [
              { id: "generator", icon: Zap,      en: "Generator", km: "បង្កើត" },
              { id: "community", icon: Users,    en: "Community", km: "សហគមន៍" },
              { id: "guide",     icon: BookOpen, en: "Guide",     km: "Guide" },
            ] as const
          ).map((t) => {
            const Icon = t.icon;
            const active = tab === t.id;
            return (
              <button
                key={t.id}
                onClick={() => setTab(t.id)}
                className="relative flex items-center gap-2 px-4 py-2.5 text-sm font-bold transition-colors"
                style={{ color: active ? "#22d3ee" : "var(--color-muted)" }}
              >
                <Icon size={15} />
                {km ? t.km : t.en}
                {active && (
                  <span
                    className="absolute -bottom-px left-0 right-0 h-0.5 rounded-full"
                    style={{ background: "linear-gradient(90deg,#22d3ee,#8b5cf6)" }}
                  />
                )}
              </button>
            );
          })}
        </div>
      </FadeIn>

      {/* ═══════════════ GENERATOR TAB ═══════════════ */}
      {tab === "generator" && (
        <FadeIn>
          <div className="grid gap-6 lg:grid-cols-[1fr_1.1fr]">
            {/* ─── LEFT: Input ─── */}
            <div
              className="rounded-2xl border p-6"
              style={{
                borderColor: "rgba(34,211,238,0.25)",
                background:
                  "linear-gradient(135deg, rgba(34,211,238,0.06) 0%, rgba(139,92,246,0.04) 100%)",
              }}
            >
              <div className="flex items-center gap-2 text-xs font-black uppercase tracking-widest" style={{ color: "#22d3ee" }}>
                <Target size={13} />
                {km ? "ឧបករណ៍របស់អ្នក" : "Your Device"}
              </div>

              {/* SEARCH */}
              <label className="mt-5 block text-xs font-bold text-muted">
                {km ? "ស្វែងរកឧបករណ៍" : "Search device"}
              </label>
              <div className="relative mt-2">
                <Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-faint" />
                <input
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  placeholder={km ? "ឧ. iPhone 15, Galaxy S24..." : "e.g. iPhone 15, Galaxy S24..."}
                  className="w-full rounded-xl border border-line bg-black/30 py-3 pl-10 pr-3 text-sm outline-none transition-colors focus:border-cyan-400/60"
                  style={{ borderColor: search ? "rgba(34,211,238,0.5)" : undefined }}
                />
                {searchResults.length > 0 && (
                  <div className="absolute left-0 right-0 top-full z-20 mt-1 max-h-64 overflow-auto rounded-xl border border-line bg-[#0d1117] shadow-2xl">
                    {searchResults.map((m) => (
                      <button
                        key={m}
                        onClick={() => pickPopular(m)}
                        className="block w-full px-4 py-2.5 text-left text-sm transition-colors hover:bg-cyan-400/10"
                      >
                        {m}
                      </button>
                    ))}
                  </div>
                )}
              </div>

              {/* QUICK SELECT */}
              <div className="mt-5">
                <div className="mb-2 flex items-center justify-between">
                  <label className="text-xs font-bold text-muted">
                    {km ? "ជ្រើសលឿន" : "Quick select"}
                  </label>
                  <span className="text-[10px] font-bold text-faint">
                    {getTotalDevices()}+ {km ? "ឧបករណ៍" : "devices"}
                  </span>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {POPULAR_MODELS.slice(0, 10).map((m) => (
                    <button
                      key={m}
                      onClick={() => pickPopular(m)}
                      className="rounded-full border px-2.5 py-1 text-[11px] font-bold transition-all"
                      style={{
                        borderColor: model === m ? "#22d3ee" : "var(--color-line)",
                        color: model === m ? "#22d3ee" : "var(--color-muted)",
                        background: model === m ? "rgba(34,211,238,0.1)" : "transparent",
                      }}
                    >
                      {m}
                    </button>
                  ))}
                </div>
              </div>

              {/* BRAND + MODEL dropdowns */}
              <div className="mt-5 grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-bold text-muted">
                    {km ? "ម៉ាក" : "Brand"}
                  </label>
                  <div className="relative mt-2">
                    <select
                      value={brand}
                      onChange={(e) => { setBrand(e.target.value); setModel(""); }}
                      className="w-full appearance-none rounded-xl border border-line bg-black/30 py-2.5 pl-3 pr-9 text-sm outline-none focus:border-cyan-400/60"
                    >
                      <option value="">— {km ? "ជ្រើស" : "Select"} —</option>
                      {BRANDS.map((b) => (
                        <option key={b} value={b}>{b}</option>
                      ))}
                    </select>
                    <ChevronDown size={14} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-faint" />
                  </div>
                </div>
                <div>
                  <label className="block text-xs font-bold text-muted">
                    {km ? "ម៉ូដែល" : "Model"}
                  </label>
                  <div className="relative mt-2">
                    <select
                      value={model}
                      onChange={(e) => setModel(e.target.value)}
                      disabled={!brand}
                      className="w-full appearance-none rounded-xl border border-line bg-black/30 py-2.5 pl-3 pr-9 text-sm outline-none focus:border-cyan-400/60 disabled:opacity-50"
                    >
                      <option value="">— {km ? "ជ្រើស" : "Select"} —</option>
                      {models.map((d) => (
                        <option key={d.model} value={d.model}>{d.model}</option>
                      ))}
                    </select>
                    <ChevronDown size={14} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-faint" />
                  </div>
                </div>
              </div>

              {/* AGE */}
              <div className="mt-5">
                <label className="block text-xs font-bold text-muted">
                  {km ? "អាយុឧបករណ៍ (ឆ្នាំ)" : "Device age (years)"}
                </label>
                <input
                  type="number"
                  min={0}
                  max={10}
                  step={0.5}
                  value={age}
                  onChange={(e) => setAge(e.target.value)}
                  className="mt-2 w-full rounded-xl border border-line bg-black/30 px-3 py-2.5 text-sm outline-none focus:border-cyan-400/60"
                />
              </div>

              {/* PLAYSTYLE */}
              <div className="mt-5">
                <label className="block text-xs font-bold text-muted">
                  {km ? "របៀបលេង" : "Playstyle"}
                </label>
                <div className="mt-2 grid grid-cols-2 gap-2">
                  {PLAYSTYLES.map((s) => {
                    const p = PLAYSTYLE_LABELS[s];
                    const active = style === s;
                    return (
                      <button
                        key={s}
                        onClick={() => setStyle(s)}
                        className="flex items-center gap-2 rounded-xl border px-3 py-2.5 text-xs font-bold transition-all"
                        style={{
                          borderColor: active ? "#22d3ee" : "var(--color-line)",
                          background: active ? "rgba(34,211,238,0.12)" : "transparent",
                          color: active ? "#22d3ee" : "var(--color-muted)",
                        }}
                      >
                        <span className="text-base">{p.emoji}</span>
                        {km ? p.km : p.en}
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* ACTIONS */}
              <div className="mt-6 flex gap-2">
                <button
                  onClick={generate}
                  disabled={!currentDevice}
                  className="flex flex-1 items-center justify-center gap-2 rounded-xl py-3 text-sm font-black transition-all disabled:opacity-40"
                  style={{
                    background: "linear-gradient(135deg,#22d3ee,#8b5cf6)",
                    color: "#0a0d14",
                  }}
                >
                  <Sparkles size={15} />
                  {km ? "បង្កើត" : "Generate"}
                </button>
                <button
                  onClick={reset}
                  className="flex items-center justify-center gap-2 rounded-xl border border-line px-4 py-3 text-sm font-bold text-muted transition-colors hover:text-fg"
                >
                  <RefreshCw size={14} />
                  {km ? "កំណត់ឡើងវិញ" : "Reset"}
                </button>
              </div>

              {currentDevice && (
                <div className="mt-3 flex items-center gap-2 text-[11px] text-faint">
                  <Info size={11} />
                  DPI: <span className="font-mono font-bold text-cyan-400">{currentDevice.dpi}</span>
                  · {TIER_LABELS[currentDevice.tier][km ? "km" : "en"]}
                </div>
              )}
            </div>

            {/* ─── RIGHT: Result ─── */}
            <div>
              {!result ? (
                <div
                  className="flex h-full min-h-[400px] flex-col items-center justify-center rounded-2xl border border-dashed p-8 text-center"
                  style={{ borderColor: "rgba(34,211,238,0.25)" }}
                >
                  <Target size={40} className="text-cyan-400/40" />
                  <p className="mt-4 text-sm font-bold text-muted">
                    {km ? "លទ្ធផលនឹងបង្ហាញនៅទីនេះ" : "Your result will appear here"}
                  </p>
                  <p className="mt-1 text-xs text-faint">
                    {km
                      ? "ជ្រើសឧបករណ៍ + របៀបលេង រួចចុច បង្កើត"
                      : "Select device + playstyle, then click Generate"}
                  </p>
                </div>
              ) : (
                <SensitivityResultCard
                  result={result}
                  model={model}
                  km={km}
                  copied={copied}
                  onCopy={copyResult}
                />
              )}
            </div>
          </div>
        </FadeIn>
      )}

      {/* ═══════════════ COMMUNITY TAB ═══════════════ */}
      {tab === "community" && (
        <FadeIn>
          <div
            className="rounded-2xl border border-dashed p-10 text-center"
            style={{ borderColor: "rgba(34,211,238,0.25)" }}
          >
            <Users size={40} className="mx-auto text-cyan-400/40" />
            <p className="mt-4 text-base font-bold">
              {km ? "មិនទាន់មាន settings ពីសហគមន៍" : "No community settings yet"}
            </p>
            <p className="mt-1 text-sm text-muted">
              {km
                ? "ក្លាយជាអ្នកដំបូងដែល share sensitivity របស់អ្នក!"
                : "Be the first to share your sensitivity!"}
            </p>
            <button
              className="mt-6 rounded-xl px-6 py-3 text-sm font-black"
              style={{ background: "linear-gradient(135deg,#22d3ee,#8b5cf6)", color: "#0a0d14" }}
            >
              {km ? "ចែករំលែករបស់ខ្ញុំ" : "Share mine"}
            </button>
          </div>
        </FadeIn>
      )}

      {/* ═══════════════ GUIDE TAB ═══════════════ */}
      {tab === "guide" && (
        <FadeIn>
          <div className="space-y-4">
            {SENSITIVITY_ROWS.map((r) => (
              <div
                key={r.key}
                className="rounded-2xl border p-5"
                style={{
                  borderColor: r.color + "40",
                  background: "linear-gradient(135deg, " + r.color + "10 0%, transparent 70%)",
                }}
              >
                <div className="flex items-center gap-3">
                  <span className="h-3 w-3 rounded-full" style={{ background: r.color }} />
                  <h3 className="text-base font-black" style={{ color: r.color }}>
                    {km ? r.km : r.en}
                  </h3>
                </div>
                <p className="mt-3 text-sm leading-relaxed text-muted">
                  {km ? GUIDE_KM[r.key] : GUIDE_EN[r.key]}
                </p>
              </div>
            ))}
          </div>
        </FadeIn>
      )}
    </div>
  );
}

// ─── Result Card ───
function SensitivityResultCard({
  result, model, km, copied, onCopy,
}: {
  result: SensitivityResult;
  model: string;
  km: boolean;
  copied: boolean;
  onCopy: () => void;
}) {
  const tier = TIER_LABELS[result.deviceTier];
  const style = PLAYSTYLE_LABELS[result.playstyle];

  return (
    <div
      className="overflow-hidden rounded-2xl border"
      style={{
        borderColor: "rgba(34,211,238,0.4)",
        background: "linear-gradient(135deg, rgba(34,211,238,0.05) 0%, rgba(139,92,246,0.03) 100%)",
        boxShadow: "0 30px 80px -40px rgba(34,211,238,0.5)",
      }}
    >
      <div className="border-b border-line p-5">
        <div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest" style={{ color: "#22d3ee" }}>
          <Target size={11} />
          {km ? "លទ្ធផល" : "Result"}
        </div>
        <h3 className="mt-2 text-lg font-black">{model}</h3>
        <div className="mt-1 flex flex-wrap items-center gap-2 text-[11px] text-muted">
          <span className="rounded-full px-2 py-0.5 font-bold" style={{ background: tier.color + "22", color: tier.color }}>
            {km ? tier.km : tier.en}
          </span>
          <span>·</span>
          <span>{style.emoji} {km ? style.km : style.en}</span>
          <span>·</span>
          <span>DPI {result.dpi}</span>
        </div>
      </div>

      <div className="divide-y divide-line">
        {SENSITIVITY_ROWS.map((r) => (
          <div key={r.key} className="flex items-center gap-3 px-5 py-3">
            <span className="h-2 w-2 rounded-full" style={{ background: r.color }} />
            <span className="flex-1 text-sm font-bold">{km ? r.km : r.en}</span>
            <span className="font-mono text-lg font-black" style={{ color: r.color }}>
              {result[r.key]}
            </span>
          </div>
        ))}
      </div>

      <div className="border-t border-line p-4">
        <button
          onClick={onCopy}
          className="flex w-full items-center justify-center gap-2 rounded-xl py-3 text-sm font-black transition-all"
          style={{
            background: copied ? "#22c55e22" : "linear-gradient(135deg,#22d3ee,#8b5cf6)",
            color: copied ? "#22c55e" : "#0a0d14",
          }}
        >
          {copied ? <Check size={15} /> : <Copy size={15} />}
          {copied
            ? (km ? "ចម្លងរួចហើយ!" : "Copied!")
            : (km ? "ចម្លងលទ្ធផល" : "Copy result")}
        </button>
      </div>
    </div>
  );
}

// ─── Guide content ───
const GUIDE_EN: Record<string, string> = {
  general: "Controls overall camera movement for hip-fire and 180° turns. Pro players use 85–100 for aggressive play, 70–80 for defensive.",
  redDot: "Affects 1x scopes like red dot and holographic. Keep it 75–90 — slightly lower than General to prevent over-aiming.",
  scope2x: "For 50–100m fights with ARs like AK47 and AN94. Recommended 60–80. Balance between aggression and stability.",
  scope4x: "For long-range 100–200m with DMRs. Recommended 40–65. Lower value gives stable recoil control.",
  sniper: "Controls 6x and 8x snipers. Keep 20–40 — lower for bolt-action like AWM, higher for semi-auto like SVD.",
  awm: "Specific for AWM bolt-action. Recommended 40–65. Precision matters more than speed — patience and calm swipes win.",
  freeLook: "Scout surroundings without changing movement direction. Recommended 80–100 for BR awareness.",
  fireButton: "Determines how fast the fire button responds. Higher = faster shots, lower = better control.",
};

const GUIDE_KM: Record<string, string> = {
  general: "គ្រប់គ្រងការបង្វិលកាមេរ៉ាទាំងមូល សម្រាប់ hip-fire និងការងាក 180°។ Pro player ប្រើ 85–100 សម្រាប់ការលេងឈ្លានពាន, 70–80 សម្រាប់ការការពារ។",
  redDot: "ប៉ះពាល់ដល់ 1x scope ដូចជា red dot និង holographic។ ទុក 75–90 — ទាបជាង General បន្តិច ដើម្បីកុំឱ្យរំកិលខ្លាំង។",
  scope2x: "សម្រាប់ការប្រយុទ្ធ 50–100m ជាមួយ AK47 និង AN94។ ណែនាំ 60–80។ សមតុល្យរវាងការឈ្លានពាន និងស្ថេរភាព។",
  scope4x: "សម្រាប់ចម្ងាយឆ្ងាយ 100–200m ជាមួយ DMR។ ណែនាំ 40–65។ តម្លៃទាបផ្តល់ការគ្រប់គ្រង recoil ស្ថិរភាព។",
  sniper: "គ្រប់គ្រង 6x និង 8x snipers។ ទុក 20–40 — ទាបសម្រាប់ bolt-action ដូច AWM, ខ្ពស់ជាងសម្រាប់ semi-auto ដូច SVD។",
  awm: "ជាពិសេសសម្រាប់ AWM bolt-action។ ណែនាំ 40–65។ ភាពជាក់លាក់សំខាន់ជាងល្បឿន — ស្ងប់ស្ងាត់និង swipes ត្រឹមត្រូវឈ្នះ។",
  freeLook: "ស្កេនជុំវិញដោយមិនប្តូរទិសដៅចលនា។ ណែនាំ 80–100 សម្រាប់ការយល់ដឹង BR។",
  fireButton: "កំណត់ថាតើ fire button ឆ្លើយតបលឿនប៉ុណ្ណា។ ខ្ពស់ = បាញ់លឿន, ទាប = គ្រប់គ្រងបានល្អ។",
};